import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { Edit, Download } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { getInitials } from '@/lib/utils';
export function ProfileHeader({ name, email, hemisId, completion, avatar, }) {
    const { t } = useTranslation();
    return (_jsx(Card, { className: "soft-surface p-6", children: _jsxs("div", { className: "flex flex-col gap-6 lg:flex-row lg:items-start lg:justify-between", children: [_jsxs("div", { className: "flex items-start gap-4", children: [_jsxs(Avatar, { className: "h-16 w-16 ring-4 ring-primary/10", children: [avatar ? _jsx(AvatarImage, { src: avatar, alt: name }) : null, _jsx(AvatarFallback, { className: "bg-primary text-primary-foreground", children: getInitials(name) })] }), _jsxs("div", { className: "space-y-1", children: [_jsx("h1", { className: "text-2xl font-bold tracking-[-0.04em] text-foreground", children: name }), _jsx("p", { className: "text-sm text-muted-foreground", children: email }), _jsxs("p", { className: "text-sm text-muted-foreground", children: [t('profile.hemisId'), ": ", hemisId] })] })] }), _jsxs("div", { className: "flex flex-col gap-3 lg:items-end", children: [_jsxs("div", { className: "lg:text-right", children: [_jsx("p", { className: "text-sm text-muted-foreground", children: t('profile.completion') }), _jsxs("div", { className: "flex items-center gap-2 mt-2", children: [_jsx("div", { className: "h-2 w-32 overflow-hidden rounded-full bg-muted", children: _jsx("div", { className: "h-full rounded-full bg-[hsl(var(--success))] transition-all", style: { width: `${completion}%` } }) }), _jsxs("span", { className: "text-sm font-medium", children: [completion, "%"] })] })] }), _jsxs("div", { className: "flex gap-2", children: [_jsxs(Button, { variant: "outline", size: "sm", className: "gap-2", children: [_jsx(Edit, { className: "h-4 w-4" }), t('common.edit')] }), _jsxs(Button, { variant: "outline", size: "sm", className: "gap-2", children: [_jsx(Download, { className: "h-4 w-4" }), t('common.export')] })] })] })] }) }));
}
